import React,{useEffect,useState} from "react";
import { supabase } from "../lib/supabase";
import type { Profesor } from "../types";
import ui from "../components/ui.module.css";

interface Props{ administrador:Profesor }

export default function Profesores({administrador}:Props){
 const [lista,setLista]=useState<Profesor[]>([]),[usuario,setUsuario]=useState(""),[nombre,setNombre]=useState(""),[pin,setPin]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 async function cargar(){const {data}=await supabase.from("bano_profesores").select("id,nombre,usuario,pin,rol").order("nombre");setLista((data??[]).map((p:any)=>({id:p.id,nombre:p.nombre,usuario:p.usuario,rol:p.rol??"profesor"})));}
 useEffect(()=>{void cargar()},[]);
 async function agregar(){const u=usuario.trim(),n=nombre.trim(),p=pin.trim();if(!u||!n||p.length!==4){setMsg("Completa usuario, nombre completo y un PIN de 4 dígitos.");return}setBusy(true);setMsg("");const {data:dup}=await supabase.from("bano_profesores").select("id").ilike("usuario",u).limit(1);if(dup?.length){setBusy(false);setMsg("Ese usuario ya existe.");return}const {error}=await supabase.from("bano_profesores").insert({usuario:u,nombre:n,pin:p,rol:"profesor"});if(error){setBusy(false);setMsg(error.message);return}setUsuario("");setNombre("");setPin("");setBusy(false);setMsg("Profesor dado de alta correctamente.");void cargar();}
 return <div className={ui.dashboard}><section className={ui.pageIntro}><div><h1 className={ui.pageTitle}>Profesores</h1><p className={ui.pageSubtitle}>Alta de cuentas para profesores.</p></div></section><section className={ui.card}><h2 className={ui.cardTitle}>Nuevo profesor</h2><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12,marginTop:16}}><div className={ui.field}><label>Usuario</label><input value={usuario} onChange={e=>setUsuario(e.target.value)} placeholder="Ej. jlopez"/></div><div className={ui.field}><label>Nombre completo</label><input value={nombre} onChange={e=>setNombre(e.target.value)} placeholder="Ej. Juan López Pérez"/></div><div className={ui.field}><label>PIN</label><input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,4))} placeholder="4 dígitos" inputMode="numeric" maxLength={4}/></div></div><button className={ui.btn+" "+ui.btnPrimary} onClick={agregar} disabled={busy}>{busy?"Guardando…":"Dar de alta profesor"}</button>{msg&&<p className={ui.errorMsg}>{msg}</p>}</section><section className={ui.card}><div className={ui.sectionHeader}><div><h2 className={ui.cardTitle}>Profesores registrados</h2><p className={ui.sectionHint}>Cuentas disponibles en el sistema.</p></div><span className={ui.countBadge}>{lista.length} cuentas</span></div><div className={ui.tableWrap}><table className={ui.statsTable}><thead><tr><th>Usuario</th><th>Nombre</th><th>Rol</th></tr></thead><tbody>{lista.map(p=><tr key={p.id}><td><strong>{p.usuario}</strong></td><td>{p.nombre}</td><td><span className={ui.groupBadge}>{p.rol==="administrador"?"Administrador":p.rol==="monitor"?"Monitor":"Profesor"}</span></td></tr>)}</tbody></table></div></section></div>;
}
